// layout.js (Server Component)
import { Inter } from "next/font/google";
import "./globals.css";
import '/lib/fontawesome';
import RootLayoutClient from './RootLayoutClient'; // Import the client-side logic

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootLayoutClient>
          {children}
        </RootLayoutClient>
      </body>
    </html>
  );
}
